FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone_ccu /drone_ccu
COPY config.ini /drone_ccu/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /drone_ccu
ENV FLASK_DEBUG=1
CMD ["python", "drone_ccu.py", "config.ini"]

EXPOSE 6072
