FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone_navigation_handler /drone_navigation_handler
COPY config.ini /drone_navigation_handler/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /drone_navigation_handler
ENV FLASK_DEBUG=1
CMD ["python", "drone_navigation_handler.py", "config.ini"]

EXPOSE 6086
