FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone_battery_control /drone_battery_control
COPY config.ini /drone_battery_control/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /drone_battery_control
ENV FLASK_DEBUG=1
CMD ["python", "drone_battery_control.py", "config.ini"]

EXPOSE 6071
