FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN apt-get update && apt-get install -y

RUN python -m pip install -r requirements.txt
#RUN echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc



COPY atm /atm

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /plc
#USER appuser

WORKDIR /atm
CMD ["python", "atm.py"]

EXPOSE 6064