FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone_flight_controller /drone_flight_controller
COPY config.ini /drone_flight_controller/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /drone_flight_controller
ENV FLASK_DEBUG=1
CMD ["python", "drone_flight_controller.py", "config.ini"]

EXPOSE 6079
