FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone /drone

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /drone
ENV FLASK_DEBUG=1
CMD ["python", "drone.py"]

EXPOSE 6066
EXPOSE 6067
EXPOSE 6068
