FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone_nav_ver /drone_nav_ver
COPY config.ini /drone_nav_ver/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /drone_nav_ver
ENV FLASK_DEBUG=1
CMD ["python", "drone_nav_ver.py", "config.ini"]

EXPOSE 6084
